### ISSUE TITLE
Overwriting Generated Files with Same Name

### ISSUE THREAD

**Issue by FXZFun** [BlackWhiteYoshi/AutoInterface#11]
When integrating AutoInterface into a project where classes share the same name but reside in different namespaces, the tool generates conflicting files with identical names in the same directory. Consequently, this leads to file overwriting, and the interfaces not being available for use in the code.

## Steps to Reproduce:
- Define two classes with the same name but residing in different namespaces
   - (e.g., `Sample.Api.V1.MyService` and `Sample.Api.V2.MyService`).
 - Annotate with the AutoInterface attribute.

## Expected Behavior:
AutoInterface should generate separate files for classes with the same name but residing in different namespaces, preserving each class's implementation without overwriting existing files, e.g.
`Sample_Api_V1_IMyService_MyService_MyService.cs.g.cs`
`Sample_Api_V2_IMyService_MyService_MyService.cs.g.cs`

## Actual Behavior:
AutoInterface generates files with the same name, leading to the overwriting of existing files.
`IMyService_MyService_MyService.cs.g.cs`

## Potential Solution:
Implement a mechanism in AutoInterface to generate unique filenames for classes with the same name but residing in different namespaces. This could involve incorporating namespace information into the generated filenames to avoid conflicts.

**Comment by BlackWhiteYoshi** [comment]
With all due respect, do you really have this issue or do you just theory crafting possible problems?

**Comment by FXZFun** [comment]
😂 I know it might seem like a small edge case, but I do actually have an API project structured in this way. I've found AutoInterface to be very useful in my other projects, so I was adding it to my API project and came across this issue. 
I see you added support already in v2.2.1, and I can confirm that solves my issue. Thanks for the speedy update!
