### ISSUE TITLE
Support for Records

### ISSUE THREAD

**Issue by ristogod** [BlackWhiteYoshi/AutoInterface#2]
I can't seem to generate an interface for a record like this:

``` csharp
[AutoInterface]
public sealed record LogService<TCategoryName>(Box Box, ILogger<TCategoryName> Logger) : ILogService<TCategoryName>;
```

**Comment by BlackWhiteYoshi** [comment]
I completely forgot about records, thank you for pointing this out. I added logic for records and the record parameterlist. In the newest version (2.0.1) it should work as expected. If you find any bugs, feel free to open another issue.
